/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

import * as RestfulShesha from '../utils/fetchers';
export const SPEC_VERSION = 'v1';
export type RefListAreaType = 1 | 2 | 3 | 4 | 5 | 6;

/**
 * Generic DTO of the simple autocomplete item
 */
export interface AutocompleteItemDto {
  value?: string | null;
  displayText?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface AutocompleteItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AutocompleteItemDto[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface ReferenceListItemValueDto {
  item?: string | null;
  itemValue?: number | null;
}

export interface AreaUpdateDto {
  id?: string;
  name?: string | null;
  shortName?: string | null;
  comments?: string | null;
  areaType?: ReferenceListItemValueDto;
}

/**
 * Generic entity Dto with display text
 */
export interface GuidNullableEntityWithDisplayNameDto {
  id?: string | null;
  /**
   * Entity display name
   */
  displayText?: string | null;
}

export interface AreaDto {
  id?: string;
  name?: string | null;
  shortName?: string | null;
  parentArea?: GuidNullableEntityWithDisplayNameDto;
  comments?: string | null;
  areaType?: ReferenceListItemValueDto;
}

export interface AreaDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AreaDto;
}

export interface GetChildAreasInput {
  id?: string | null;
}

export interface AreaTreeItemDto {
  id?: string;
  name?: string | null;
  parentId?: string | null;
  hasChilds?: boolean;
}

export interface AreaTreeItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AreaTreeItemDto[] | null;
}

export interface GuidEntityDto {
  id?: string;
}

export interface AreaTreeItemDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AreaTreeItemDto;
}

export interface MoveAreaInput {
  id?: string;
  newParentId?: string | null;
}

export interface AreaCreateDto {
  name?: string | null;
  shortName?: string | null;
  parentArea?: GuidNullableEntityWithDisplayNameDto;
  comments?: string | null;
  areaType?: ReferenceListItemValueDto;
}

export interface AreaDtoPagedResultDto {
  items?: AreaDto[] | null;
  totalCount?: number;
}

export interface AreaDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AreaDtoPagedResultDto;
}

export interface AreaAutocompleteQueryParams {
  term?: string | null;
  areaType?: RefListAreaType;
  parentAreaId?: string | null;
}

export type AreaAutocompleteProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaAutocompleteQueryParams, void>,
  'path'
>;

export const AreaAutocomplete = (props: AreaAutocompleteProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaAutocompleteQueryParams, void>
    path={`/api/services/app/Area/Autocomplete`}
    {...props}
  />
);

export type UseAreaAutocompleteProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaAutocompleteQueryParams, void>,
  'path'
>;

export const useAreaAutocomplete = (props: UseAreaAutocompleteProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaAutocompleteQueryParams, void>(
    `/api/services/app/Area/Autocomplete`,
    props
  );

export type areaAutocompleteProps = Omit<
  RestfulShesha.GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaAutocompleteQueryParams, void>,
  'queryParams'
>;
export const areaAutocomplete = (queryParams: AreaAutocompleteQueryParams, props: areaAutocompleteProps) =>
  RestfulShesha.get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaAutocompleteQueryParams, void>(
    `/api/services/app/Area/Autocomplete`,
    queryParams,
    props
  );

export interface AreaCascadeSelectQueryParams {
  areaType?: RefListAreaType;
  parentAreaId?: string | null;
}

export type AreaCascadeSelectProps = Omit<
  GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaCascadeSelectQueryParams, void>,
  'path'
>;

export const AreaCascadeSelect = (props: AreaCascadeSelectProps) => (
  <Get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaCascadeSelectQueryParams, void>
    path={`/api/services/app/Area/CascadeSelect`}
    {...props}
  />
);

export type UseAreaCascadeSelectProps = Omit<
  UseGetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaCascadeSelectQueryParams, void>,
  'path'
>;

export const useAreaCascadeSelect = (props: UseAreaCascadeSelectProps) =>
  useGet<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaCascadeSelectQueryParams, void>(
    `/api/services/app/Area/CascadeSelect`,
    props
  );

export type areaCascadeSelectProps = Omit<
  RestfulShesha.GetProps<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaCascadeSelectQueryParams, void>,
  'queryParams'
>;
export const areaCascadeSelect = (queryParams: AreaCascadeSelectQueryParams, props: areaCascadeSelectProps) =>
  RestfulShesha.get<AutocompleteItemDtoListAjaxResponse, AjaxResponseBase, AreaCascadeSelectQueryParams, void>(
    `/api/services/app/Area/CascadeSelect`,
    queryParams,
    props
  );

export type AreaUpdateProps = Omit<
  MutateProps<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaUpdateDto, void>,
  'path' | 'verb'
>;

export const AreaUpdate = (props: AreaUpdateProps) => (
  <Mutate<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaUpdateDto, void>
    verb="PUT"
    path={`/api/services/app/Area/Update`}
    {...props}
  />
);

export type UseAreaUpdateProps = Omit<
  UseMutateProps<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaUpdateDto, void>,
  'path' | 'verb'
>;

export const useAreaUpdate = (props: UseAreaUpdateProps) =>
  useMutate<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaUpdateDto, void>(
    'PUT',
    `/api/services/app/Area/Update`,
    props
  );

export type areaUpdateProps = Omit<
  RestfulShesha.MutateProps<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaUpdateDto, void>,
  'data'
>;
export const areaUpdate = (data: AreaUpdateDto, props: areaUpdateProps) =>
  RestfulShesha.mutate<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaUpdateDto, void>(
    'PUT',
    `/api/services/app/Area/Update`,
    data,
    props
  );

export interface AreaGetQueryParams {
  id?: string;
}

export type AreaGetProps = Omit<GetProps<AreaDtoAjaxResponse, AjaxResponseBase, AreaGetQueryParams, void>, 'path'>;

export const AreaGet = (props: AreaGetProps) => (
  <Get<AreaDtoAjaxResponse, AjaxResponseBase, AreaGetQueryParams, void>
    path={`/api/services/app/Area/Get`}
    {...props}
  />
);

export type UseAreaGetProps = Omit<
  UseGetProps<AreaDtoAjaxResponse, AjaxResponseBase, AreaGetQueryParams, void>,
  'path'
>;

export const useAreaGet = (props: UseAreaGetProps) =>
  useGet<AreaDtoAjaxResponse, AjaxResponseBase, AreaGetQueryParams, void>(`/api/services/app/Area/Get`, props);

export type areaGetProps = Omit<
  RestfulShesha.GetProps<AreaDtoAjaxResponse, AjaxResponseBase, AreaGetQueryParams, void>,
  'queryParams'
>;
export const areaGet = (queryParams: AreaGetQueryParams, props: areaGetProps) =>
  RestfulShesha.get<AreaDtoAjaxResponse, AjaxResponseBase, AreaGetQueryParams, void>(
    `/api/services/app/Area/Get`,
    queryParams,
    props
  );

export type AreaGetChildTreeItemsProps = Omit<
  MutateProps<AreaTreeItemDtoListAjaxResponse, AjaxResponseBase, void, GetChildAreasInput, void>,
  'path' | 'verb'
>;

/**
 * Returns child areas of the specified parent
 */
export const AreaGetChildTreeItems = (props: AreaGetChildTreeItemsProps) => (
  <Mutate<AreaTreeItemDtoListAjaxResponse, AjaxResponseBase, void, GetChildAreasInput, void>
    verb="POST"
    path={`/api/services/app/Area/GetChildTreeItems`}
    {...props}
  />
);

export type UseAreaGetChildTreeItemsProps = Omit<
  UseMutateProps<AreaTreeItemDtoListAjaxResponse, AjaxResponseBase, void, GetChildAreasInput, void>,
  'path' | 'verb'
>;

/**
 * Returns child areas of the specified parent
 */
export const useAreaGetChildTreeItems = (props: UseAreaGetChildTreeItemsProps) =>
  useMutate<AreaTreeItemDtoListAjaxResponse, AjaxResponseBase, void, GetChildAreasInput, void>(
    'POST',
    `/api/services/app/Area/GetChildTreeItems`,
    props
  );

export type areaGetChildTreeItemsProps = Omit<
  RestfulShesha.MutateProps<AreaTreeItemDtoListAjaxResponse, AjaxResponseBase, void, GetChildAreasInput, void>,
  'data'
>;
/**
 * Returns child areas of the specified parent
 */
export const areaGetChildTreeItems = (data: GetChildAreasInput, props: areaGetChildTreeItemsProps) =>
  RestfulShesha.mutate<AreaTreeItemDtoListAjaxResponse, AjaxResponseBase, void, GetChildAreasInput, void>(
    'POST',
    `/api/services/app/Area/GetChildTreeItems`,
    data,
    props
  );

export type AreaGetTreeItemProps = Omit<
  MutateProps<AreaTreeItemDtoAjaxResponse, AjaxResponseBase, void, GuidEntityDto, void>,
  'path' | 'verb'
>;

/**
 * Returns child areas of the specified parent
 */
export const AreaGetTreeItem = (props: AreaGetTreeItemProps) => (
  <Mutate<AreaTreeItemDtoAjaxResponse, AjaxResponseBase, void, GuidEntityDto, void>
    verb="POST"
    path={`/api/services/app/Area/GetTreeItem`}
    {...props}
  />
);

export type UseAreaGetTreeItemProps = Omit<
  UseMutateProps<AreaTreeItemDtoAjaxResponse, AjaxResponseBase, void, GuidEntityDto, void>,
  'path' | 'verb'
>;

/**
 * Returns child areas of the specified parent
 */
export const useAreaGetTreeItem = (props: UseAreaGetTreeItemProps) =>
  useMutate<AreaTreeItemDtoAjaxResponse, AjaxResponseBase, void, GuidEntityDto, void>(
    'POST',
    `/api/services/app/Area/GetTreeItem`,
    props
  );

export type areaGetTreeItemProps = Omit<
  RestfulShesha.MutateProps<AreaTreeItemDtoAjaxResponse, AjaxResponseBase, void, GuidEntityDto, void>,
  'data'
>;
/**
 * Returns child areas of the specified parent
 */
export const areaGetTreeItem = (data: GuidEntityDto, props: areaGetTreeItemProps) =>
  RestfulShesha.mutate<AreaTreeItemDtoAjaxResponse, AjaxResponseBase, void, GuidEntityDto, void>(
    'POST',
    `/api/services/app/Area/GetTreeItem`,
    data,
    props
  );

export type AreaDeleteProps = Omit<MutateProps<void, unknown, void, GuidEntityDto, void>, 'path' | 'verb'>;

export const AreaDelete = (props: AreaDeleteProps) => (
  <Mutate<void, unknown, void, GuidEntityDto, void> verb="POST" path={`/api/services/app/Area/Delete`} {...props} />
);

export type UseAreaDeleteProps = Omit<UseMutateProps<void, unknown, void, GuidEntityDto, void>, 'path' | 'verb'>;

export const useAreaDelete = (props: UseAreaDeleteProps) =>
  useMutate<void, unknown, void, GuidEntityDto, void>('POST', `/api/services/app/Area/Delete`, props);

export type areaDeleteProps = Omit<RestfulShesha.MutateProps<void, unknown, void, GuidEntityDto, void>, 'data'>;
export const areaDelete = (data: GuidEntityDto, props: areaDeleteProps) =>
  RestfulShesha.mutate<void, unknown, void, GuidEntityDto, void>('POST', `/api/services/app/Area/Delete`, data, props);

export type AreaMoveAreaProps = Omit<MutateProps<void, unknown, void, MoveAreaInput, void>, 'path' | 'verb'>;

/**
 * Moves Area to a new parent
 */
export const AreaMoveArea = (props: AreaMoveAreaProps) => (
  <Mutate<void, unknown, void, MoveAreaInput, void> verb="POST" path={`/api/services/app/Area/MoveArea`} {...props} />
);

export type UseAreaMoveAreaProps = Omit<UseMutateProps<void, unknown, void, MoveAreaInput, void>, 'path' | 'verb'>;

/**
 * Moves Area to a new parent
 */
export const useAreaMoveArea = (props: UseAreaMoveAreaProps) =>
  useMutate<void, unknown, void, MoveAreaInput, void>('POST', `/api/services/app/Area/MoveArea`, props);

export type areaMoveAreaProps = Omit<RestfulShesha.MutateProps<void, unknown, void, MoveAreaInput, void>, 'data'>;
/**
 * Moves Area to a new parent
 */
export const areaMoveArea = (data: MoveAreaInput, props: areaMoveAreaProps) =>
  RestfulShesha.mutate<void, unknown, void, MoveAreaInput, void>(
    'POST',
    `/api/services/app/Area/MoveArea`,
    data,
    props
  );

export type AreaCreateProps = Omit<
  MutateProps<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaCreateDto, void>,
  'path' | 'verb'
>;

export const AreaCreate = (props: AreaCreateProps) => (
  <Mutate<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaCreateDto, void>
    verb="POST"
    path={`/api/services/app/Area/Create`}
    {...props}
  />
);

export type UseAreaCreateProps = Omit<
  UseMutateProps<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaCreateDto, void>,
  'path' | 'verb'
>;

export const useAreaCreate = (props: UseAreaCreateProps) =>
  useMutate<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaCreateDto, void>(
    'POST',
    `/api/services/app/Area/Create`,
    props
  );

export type areaCreateProps = Omit<
  RestfulShesha.MutateProps<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaCreateDto, void>,
  'data'
>;
export const areaCreate = (data: AreaCreateDto, props: areaCreateProps) =>
  RestfulShesha.mutate<AreaDtoAjaxResponse, AjaxResponseBase, void, AreaCreateDto, void>(
    'POST',
    `/api/services/app/Area/Create`,
    data,
    props
  );

export interface AreaGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
}

export type AreaGetAllProps = Omit<
  GetProps<AreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, AreaGetAllQueryParams, void>,
  'path'
>;

export const AreaGetAll = (props: AreaGetAllProps) => (
  <Get<AreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, AreaGetAllQueryParams, void>
    path={`/api/services/app/Area/GetAll`}
    {...props}
  />
);

export type UseAreaGetAllProps = Omit<
  UseGetProps<AreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, AreaGetAllQueryParams, void>,
  'path'
>;

export const useAreaGetAll = (props: UseAreaGetAllProps) =>
  useGet<AreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, AreaGetAllQueryParams, void>(
    `/api/services/app/Area/GetAll`,
    props
  );

export type areaGetAllProps = Omit<
  RestfulShesha.GetProps<AreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, AreaGetAllQueryParams, void>,
  'queryParams'
>;
export const areaGetAll = (queryParams: AreaGetAllQueryParams, props: areaGetAllProps) =>
  RestfulShesha.get<AreaDtoPagedResultDtoAjaxResponse, AjaxResponseBase, AreaGetAllQueryParams, void>(
    `/api/services/app/Area/GetAll`,
    queryParams,
    props
  );
