/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export interface GuidEntityDto {
  id?: string;
}

/**
 * Check list item DTO for tree component
 */
export interface CheckListTreeItemDto {
  id?: string;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Parent Id
   */
  parentId?: string | null;
  /**
   * Order Index
   */
  orderIndex?: number;
  /**
   * If true, indicates that item has child items
   */
  hasChilds?: boolean;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface CheckListTreeItemDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: CheckListTreeItemDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

/**
 * Input to get child check list items
 */
export interface GetChildCheckListItemsInput {
  /**
   * Id of the checklist
   */
  checkListId?: string;
  /**
   * Id of the parent item
   */
  parentId?: string | null;
}

export interface CheckListTreeItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: CheckListTreeItemDto[] | null;
}

/**
 * Move check list item input
 */
export interface UpdateChildItemsInput {
  /**
   * Id of the check list
   */
  checkListId?: string;
  /**
   * Id of the new parent item
   */
  parentId?: string | null;
  /**
   * List of child item ids
   */
  childIds?: string[] | null;
}

export interface ReferenceListItemValueDto {
  item?: string | null;
  itemValue?: number | null;
}

/**
 * CheckListItem DTO
 */
export interface CheckListItemDto {
  id?: string;
  /**
   * Id of the check list which current item belongs to
   */
  checkListId?: string;
  /**
   * Parent item id
   */
  parentId?: string | null;
  /**
   * Order index of the item
   */
  orderIndex?: number;
  itemType?: ReferenceListItemValueDto;
  /**
   * Item name
   */
  name?: string | null;
  /**
   * Item description
   */
  description?: string | null;
  /**
   * If true, the user is able to add comments to this item/group
   */
  allowAddComments?: boolean;
  /**
   * Heading of the comments box
   */
  commentsHeading?: string | null;
  /**
   * Custom visibility of comments (javascript expression)
   */
  commentsVisibilityExpression?: string | null;
}

export interface CheckListItemDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: CheckListItemDto;
}

export interface CheckListItemDtoPagedResultDto {
  items?: CheckListItemDto[] | null;
  totalCount?: number;
}

export interface CheckListItemDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: CheckListItemDtoPagedResultDto;
}

export interface CheckListItemGetTreeItemQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListItemGetTreeItemProps = Omit<
  MutateProps<CheckListTreeItemDtoAjaxResponse, AjaxResponseBase, CheckListItemGetTreeItemQueryParams, GuidEntityDto>,
  'path' | 'verb'
>;

/**
 * Returns child areas of the specified parent
 */
export const CheckListItemGetTreeItem = (props: CheckListItemGetTreeItemProps) => (
  <Mutate<CheckListTreeItemDtoAjaxResponse, AjaxResponseBase, CheckListItemGetTreeItemQueryParams, GuidEntityDto>
    verb="POST"
    path={`/api/services/app/CheckListItem/GetTreeItem`}
    {...props}
  />
);

export type UseCheckListItemGetTreeItemProps = Omit<
  UseMutateProps<CheckListTreeItemDtoAjaxResponse, CheckListItemGetTreeItemQueryParams, GuidEntityDto>,
  'path' | 'verb'
>;

/**
 * Returns child areas of the specified parent
 */
export const useCheckListItemGetTreeItem = (props: UseCheckListItemGetTreeItemProps) =>
  useMutate<CheckListTreeItemDtoAjaxResponse, AjaxResponseBase, CheckListItemGetTreeItemQueryParams, GuidEntityDto>(
    'POST',
    `/api/services/app/CheckListItem/GetTreeItem`,
    props
  );

export interface CheckListItemGetChildTreeItemsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListItemGetChildTreeItemsProps = Omit<
  MutateProps<
    CheckListTreeItemDtoListAjaxResponse,
    AjaxResponseBase,
    CheckListItemGetChildTreeItemsQueryParams,
    GetChildCheckListItemsInput
  >,
  'path' | 'verb'
>;

/**
 * Returns child items of the specified parent
 */
export const CheckListItemGetChildTreeItems = (props: CheckListItemGetChildTreeItemsProps) => (
  <Mutate<
    CheckListTreeItemDtoListAjaxResponse,
    AjaxResponseBase,
    CheckListItemGetChildTreeItemsQueryParams,
    GetChildCheckListItemsInput
  >
    verb="POST"
    path={`/api/services/app/CheckListItem/GetChildTreeItems`}
    {...props}
  />
);

export type UseCheckListItemGetChildTreeItemsProps = Omit<
  UseMutateProps<
    CheckListTreeItemDtoListAjaxResponse,
    CheckListItemGetChildTreeItemsQueryParams,
    GetChildCheckListItemsInput
  >,
  'path' | 'verb'
>;

/**
 * Returns child items of the specified parent
 */
export const useCheckListItemGetChildTreeItems = (props: UseCheckListItemGetChildTreeItemsProps) =>
  useMutate<
    CheckListTreeItemDtoListAjaxResponse,
    AjaxResponseBase,
    CheckListItemGetChildTreeItemsQueryParams,
    GetChildCheckListItemsInput
  >('POST', `/api/services/app/CheckListItem/GetChildTreeItems`, props);

export interface CheckListItemUpdateChildItemsQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListItemUpdateChildItemsProps = Omit<
  MutateProps<void, unknown, CheckListItemUpdateChildItemsQueryParams, UpdateChildItemsInput>,
  'path' | 'verb'
>;

/**
 * Moves Area to a new parent
 */
export const CheckListItemUpdateChildItems = (props: CheckListItemUpdateChildItemsProps) => (
  <Mutate<void, unknown, CheckListItemUpdateChildItemsQueryParams, UpdateChildItemsInput>
    verb="POST"
    path={`/api/services/app/CheckListItem/UpdateChildItems`}
    {...props}
  />
);

export type UseCheckListItemUpdateChildItemsProps = Omit<
  UseMutateProps<void, CheckListItemUpdateChildItemsQueryParams, UpdateChildItemsInput>,
  'path' | 'verb'
>;

/**
 * Moves Area to a new parent
 */
export const useCheckListItemUpdateChildItems = (props: UseCheckListItemUpdateChildItemsProps) =>
  useMutate<void, unknown, CheckListItemUpdateChildItemsQueryParams, UpdateChildItemsInput>(
    'POST',
    `/api/services/app/CheckListItem/UpdateChildItems`,
    props
  );

export interface CheckListItemDeleteQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListItemDeleteProps = Omit<
  MutateProps<void, unknown, CheckListItemDeleteQueryParams, void>,
  'path' | 'verb'
>;

export const CheckListItemDelete = (props: CheckListItemDeleteProps) => (
  <Mutate<void, unknown, CheckListItemDeleteQueryParams, void>
    verb="DELETE"
    path={`/api/services/app/CheckListItem/Delete`}
    {...props}
  />
);

export type UseCheckListItemDeleteProps = Omit<
  UseMutateProps<void, CheckListItemDeleteQueryParams, void>,
  'path' | 'verb'
>;

export const useCheckListItemDelete = (props: UseCheckListItemDeleteProps) =>
  useMutate<void, unknown, CheckListItemDeleteQueryParams, void>(
    'DELETE',
    `/api/services/app/CheckListItem/Delete`,
    props
  );

export interface CheckListItemGetQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListItemGetProps = Omit<
  GetProps<CheckListItemDtoAjaxResponse, AjaxResponseBase, CheckListItemGetQueryParams>,
  'path'
>;

export const CheckListItemGet = (props: CheckListItemGetProps) => (
  <Get<CheckListItemDtoAjaxResponse, AjaxResponseBase, CheckListItemGetQueryParams>
    path={`/api/services/app/CheckListItem/Get`}
    {...props}
  />
);

export type UseCheckListItemGetProps = Omit<
  UseGetProps<CheckListItemDtoAjaxResponse, CheckListItemGetQueryParams>,
  'path'
>;

export const useCheckListItemGet = (props: UseCheckListItemGetProps) =>
  useGet<CheckListItemDtoAjaxResponse, AjaxResponseBase, CheckListItemGetQueryParams>(
    `/api/services/app/CheckListItem/Get`,
    props
  );

export interface CheckListItemGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListItemGetAllProps = Omit<
  GetProps<CheckListItemDtoPagedResultDtoAjaxResponse, AjaxResponseBase, CheckListItemGetAllQueryParams>,
  'path'
>;

export const CheckListItemGetAll = (props: CheckListItemGetAllProps) => (
  <Get<CheckListItemDtoPagedResultDtoAjaxResponse, AjaxResponseBase, CheckListItemGetAllQueryParams>
    path={`/api/services/app/CheckListItem/GetAll`}
    {...props}
  />
);

export type UseCheckListItemGetAllProps = Omit<
  UseGetProps<CheckListItemDtoPagedResultDtoAjaxResponse, CheckListItemGetAllQueryParams>,
  'path'
>;

export const useCheckListItemGetAll = (props: UseCheckListItemGetAllProps) =>
  useGet<CheckListItemDtoPagedResultDtoAjaxResponse, AjaxResponseBase, CheckListItemGetAllQueryParams>(
    `/api/services/app/CheckListItem/GetAll`,
    props
  );

export interface CheckListItemCreateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListItemCreateProps = Omit<
  MutateProps<CheckListItemDtoAjaxResponse, AjaxResponseBase, CheckListItemCreateQueryParams, CheckListItemDto>,
  'path' | 'verb'
>;

export const CheckListItemCreate = (props: CheckListItemCreateProps) => (
  <Mutate<CheckListItemDtoAjaxResponse, AjaxResponseBase, CheckListItemCreateQueryParams, CheckListItemDto>
    verb="POST"
    path={`/api/services/app/CheckListItem/Create`}
    {...props}
  />
);

export type UseCheckListItemCreateProps = Omit<
  UseMutateProps<CheckListItemDtoAjaxResponse, CheckListItemCreateQueryParams, CheckListItemDto>,
  'path' | 'verb'
>;

export const useCheckListItemCreate = (props: UseCheckListItemCreateProps) =>
  useMutate<CheckListItemDtoAjaxResponse, AjaxResponseBase, CheckListItemCreateQueryParams, CheckListItemDto>(
    'POST',
    `/api/services/app/CheckListItem/Create`,
    props
  );

export interface CheckListItemUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListItemUpdateProps = Omit<
  MutateProps<CheckListItemDtoAjaxResponse, AjaxResponseBase, CheckListItemUpdateQueryParams, CheckListItemDto>,
  'path' | 'verb'
>;

export const CheckListItemUpdate = (props: CheckListItemUpdateProps) => (
  <Mutate<CheckListItemDtoAjaxResponse, AjaxResponseBase, CheckListItemUpdateQueryParams, CheckListItemDto>
    verb="PUT"
    path={`/api/services/app/CheckListItem/Update`}
    {...props}
  />
);

export type UseCheckListItemUpdateProps = Omit<
  UseMutateProps<CheckListItemDtoAjaxResponse, CheckListItemUpdateQueryParams, CheckListItemDto>,
  'path' | 'verb'
>;

export const useCheckListItemUpdate = (props: UseCheckListItemUpdateProps) =>
  useMutate<CheckListItemDtoAjaxResponse, AjaxResponseBase, CheckListItemUpdateQueryParams, CheckListItemDto>(
    'PUT',
    `/api/services/app/CheckListItem/Update`,
    props
  );
