/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

/**
 * Check list item selection made by the user
 */
export interface CheckListItemSelectionDto {
  /**
   * Check list item id
   */
  checkListItemId?: string;
  /**
   * User selection (yes = 1, no = 2, na = 3), see Shesha.Domain.Enums.RefListCheckListSelectionType
   */
  selection?: number | null;
  /**
   * User comments
   */
  comments?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface CheckListItemSelectionDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: CheckListItemSelectionDto[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

/**
 * Save check list selection input
 */
export interface SaveSelectionInput {
  /**
   * Owner entity Id
   */
  id: string;
  /**
   * Owner entity type short alias
   */
  ownerType: string;
  /**
   * Check list id
   */
  ownerId: string;
  /**
   * User selection
   */
  selection: CheckListItemSelectionDto[];
}

/**
 * Check list item model
 */
export interface CheckListItemModel {
  id?: string;
  /**
   * Item type (group = 1, two state = 2, tri state = 3), see Shesha.Domain.Enums.RefListCheckListItemType
   */
  itemType?: number;
  /**
   * Item name
   */
  name?: string | null;
  /**
   * Item description
   */
  description?: string | null;
  /**
   * If true, the user is able to add comments to this item/group
   */
  allowAddComments?: boolean;
  /**
   * Heading of the comments box
   */
  commentsHeading?: string | null;
  /**
   * Custom visibility of comments (javascript expression)
   */
  commentsVisibilityExpression?: string | null;
  /**
   * Child items
   */
  childItems?: CheckListItemModel[] | null;
}

/**
 * Checklist model
 */
export interface CheckListModel {
  id?: string;
  /**
   * Name of the check list
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Items of the check list
   */
  items?: CheckListItemModel[] | null;
}

export interface CheckListModelAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: CheckListModel;
}

/**
 * CheckList DTO
 */
export interface CheckListDto {
  id?: string;
  /**
   * Name of the check list
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
}

export interface CheckListDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: CheckListDto;
}

export interface CheckListDtoPagedResultDto {
  items?: CheckListDto[] | null;
  totalCount?: number;
}

export interface CheckListDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: CheckListDtoPagedResultDto;
}

export interface CheckListGetSelectionQueryParams {
  /**
   * Owner entity type short alias
   */
  ownerType: string;
  /**
   * Owner entity Id
   */
  ownerId: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListGetSelectionProps = Omit<
  GetProps<CheckListItemSelectionDtoListAjaxResponse, AjaxResponseBase, CheckListGetSelectionQueryParams>,
  'path'
> & { id: string };

/**
 * Get user selection
 */
export const CheckListGetSelection = ({ id, ...props }: CheckListGetSelectionProps) => (
  <Get<CheckListItemSelectionDtoListAjaxResponse, AjaxResponseBase, CheckListGetSelectionQueryParams>
    path={`/checkList/${id}/selection`}
    {...props}
  />
);

export type UseCheckListGetSelectionProps = Omit<
  UseGetProps<CheckListItemSelectionDtoListAjaxResponse, CheckListGetSelectionQueryParams>,
  'path'
> & { id: string };

/**
 * Get user selection
 */
export const useCheckListGetSelection = ({ id, ...props }: UseCheckListGetSelectionProps) =>
  useGet<CheckListItemSelectionDtoListAjaxResponse, AjaxResponseBase, CheckListGetSelectionQueryParams>(
    `/checkList/${id}/selection`,
    props
  );

export interface CheckListSaveSelectionQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListSaveSelectionProps = Omit<
  MutateProps<void, unknown, CheckListSaveSelectionQueryParams, SaveSelectionInput>,
  'path' | 'verb'
> & { id: string };

/**
 * Save user selection
 */
export const CheckListSaveSelection = ({ id, ...props }: CheckListSaveSelectionProps) => (
  <Mutate<void, unknown, CheckListSaveSelectionQueryParams, SaveSelectionInput>
    verb="POST"
    path={`/checkList/${id}/selection`}
    {...props}
  />
);

export type UseCheckListSaveSelectionProps = Omit<
  UseMutateProps<void, CheckListSaveSelectionQueryParams, SaveSelectionInput>,
  'path' | 'verb'
> & { id: string };

/**
 * Save user selection
 */
export const useCheckListSaveSelection = ({ id, ...props }: UseCheckListSaveSelectionProps) =>
  useMutate<void, unknown, CheckListSaveSelectionQueryParams, SaveSelectionInput>(
    'POST',
    `/checkList/${id}/selection`,
    props
  );

export interface CheckListGetCheckListTreeQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListGetCheckListTreeProps = Omit<
  GetProps<CheckListModelAjaxResponse, AjaxResponseBase, CheckListGetCheckListTreeQueryParams>,
  'path'
> & { id: string };

/**
 * Get check list tree
 */
export const CheckListGetCheckListTree = ({ id, ...props }: CheckListGetCheckListTreeProps) => (
  <Get<CheckListModelAjaxResponse, AjaxResponseBase, CheckListGetCheckListTreeQueryParams>
    path={`/checkList/${id}/tree`}
    {...props}
  />
);

export type UseCheckListGetCheckListTreeProps = Omit<
  UseGetProps<CheckListModelAjaxResponse, CheckListGetCheckListTreeQueryParams>,
  'path'
> & { id: string };

/**
 * Get check list tree
 */
export const useCheckListGetCheckListTree = ({ id, ...props }: UseCheckListGetCheckListTreeProps) =>
  useGet<CheckListModelAjaxResponse, AjaxResponseBase, CheckListGetCheckListTreeQueryParams>(
    `/checkList/${id}/tree`,
    props
  );

export interface CheckListGetQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListGetProps = Omit<
  GetProps<CheckListDtoAjaxResponse, AjaxResponseBase, CheckListGetQueryParams>,
  'path'
>;

export const CheckListGet = (props: CheckListGetProps) => (
  <Get<CheckListDtoAjaxResponse, AjaxResponseBase, CheckListGetQueryParams>
    path={`/api/services/app/CheckList/Get`}
    {...props}
  />
);

export type UseCheckListGetProps = Omit<UseGetProps<CheckListDtoAjaxResponse, CheckListGetQueryParams>, 'path'>;

export const useCheckListGet = (props: UseCheckListGetProps) =>
  useGet<CheckListDtoAjaxResponse, AjaxResponseBase, CheckListGetQueryParams>(`/api/services/app/CheckList/Get`, props);

export interface CheckListGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListGetAllProps = Omit<
  GetProps<CheckListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, CheckListGetAllQueryParams>,
  'path'
>;

export const CheckListGetAll = (props: CheckListGetAllProps) => (
  <Get<CheckListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, CheckListGetAllQueryParams>
    path={`/api/services/app/CheckList/GetAll`}
    {...props}
  />
);

export type UseCheckListGetAllProps = Omit<
  UseGetProps<CheckListDtoPagedResultDtoAjaxResponse, CheckListGetAllQueryParams>,
  'path'
>;

export const useCheckListGetAll = (props: UseCheckListGetAllProps) =>
  useGet<CheckListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, CheckListGetAllQueryParams>(
    `/api/services/app/CheckList/GetAll`,
    props
  );

export interface CheckListCreateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListCreateProps = Omit<
  MutateProps<CheckListDtoAjaxResponse, AjaxResponseBase, CheckListCreateQueryParams, CheckListDto>,
  'path' | 'verb'
>;

export const CheckListCreate = (props: CheckListCreateProps) => (
  <Mutate<CheckListDtoAjaxResponse, AjaxResponseBase, CheckListCreateQueryParams, CheckListDto>
    verb="POST"
    path={`/api/services/app/CheckList/Create`}
    {...props}
  />
);

export type UseCheckListCreateProps = Omit<
  UseMutateProps<CheckListDtoAjaxResponse, CheckListCreateQueryParams, CheckListDto>,
  'path' | 'verb'
>;

export const useCheckListCreate = (props: UseCheckListCreateProps) =>
  useMutate<CheckListDtoAjaxResponse, AjaxResponseBase, CheckListCreateQueryParams, CheckListDto>(
    'POST',
    `/api/services/app/CheckList/Create`,
    props
  );

export interface CheckListUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListUpdateProps = Omit<
  MutateProps<CheckListDtoAjaxResponse, AjaxResponseBase, CheckListUpdateQueryParams, CheckListDto>,
  'path' | 'verb'
>;

export const CheckListUpdate = (props: CheckListUpdateProps) => (
  <Mutate<CheckListDtoAjaxResponse, AjaxResponseBase, CheckListUpdateQueryParams, CheckListDto>
    verb="PUT"
    path={`/api/services/app/CheckList/Update`}
    {...props}
  />
);

export type UseCheckListUpdateProps = Omit<
  UseMutateProps<CheckListDtoAjaxResponse, CheckListUpdateQueryParams, CheckListDto>,
  'path' | 'verb'
>;

export const useCheckListUpdate = (props: UseCheckListUpdateProps) =>
  useMutate<CheckListDtoAjaxResponse, AjaxResponseBase, CheckListUpdateQueryParams, CheckListDto>(
    'PUT',
    `/api/services/app/CheckList/Update`,
    props
  );

export interface CheckListDeleteQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type CheckListDeleteProps = Omit<MutateProps<void, unknown, CheckListDeleteQueryParams, void>, 'path' | 'verb'>;

export const CheckListDelete = (props: CheckListDeleteProps) => (
  <Mutate<void, unknown, CheckListDeleteQueryParams, void>
    verb="DELETE"
    path={`/api/services/app/CheckList/Delete`}
    {...props}
  />
);

export type UseCheckListDeleteProps = Omit<UseMutateProps<void, CheckListDeleteQueryParams, void>, 'path' | 'verb'>;

export const useCheckListDelete = (props: UseCheckListDeleteProps) =>
  useMutate<void, unknown, CheckListDeleteQueryParams, void>('DELETE', `/api/services/app/CheckList/Delete`, props);
