/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

/**
 * Configurable Component DTO
 */
export interface ConfigurableComponentDto {
  id?: string;
  /**
   * Form path/id is used to identify a form
   */
  path?: string | null;
  /**
   * Form name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Settings in JSON format
   */
  settings?: string | null;
  /**
   * Type of the form model
   */
  modelType?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface ConfigurableComponentDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ConfigurableComponentDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

/**
 * Update component settings input
 */
export interface ConfigurableComponentUpdateSettingsInput {
  id?: string;
  /**
   * Settings in JSON format
   */
  settings?: string | null;
}

export type ConfigurableComponentGetProps = Omit<
  GetProps<ConfigurableComponentDtoAjaxResponse, AjaxResponseBase, void>,
  'path'
> & { id: string };

export const ConfigurableComponentGet = ({ id, ...props }: ConfigurableComponentGetProps) => (
  <Get<ConfigurableComponentDtoAjaxResponse, AjaxResponseBase, void>
    path={`/api/services/ConfigurableComponents/${id}`}
    {...props}
  />
);

export type UseConfigurableComponentGetProps = Omit<UseGetProps<ConfigurableComponentDtoAjaxResponse, void>, 'path'> & {
  id: string;
};

export const useConfigurableComponentGet = ({ id, ...props }: UseConfigurableComponentGetProps) =>
  useGet<ConfigurableComponentDtoAjaxResponse, AjaxResponseBase, void>(
    `/api/services/ConfigurableComponents/${id}`,
    props
  );

export type ConfigurableComponentUpdateProps = Omit<
  MutateProps<ConfigurableComponentDtoAjaxResponse, AjaxResponseBase, void, ConfigurableComponentDto>,
  'path' | 'verb'
>;

export const ConfigurableComponentUpdate = (props: ConfigurableComponentUpdateProps) => (
  <Mutate<ConfigurableComponentDtoAjaxResponse, AjaxResponseBase, void, ConfigurableComponentDto>
    verb="PUT"
    path={`/api/services/ConfigurableComponents`}
    {...props}
  />
);

export type UseConfigurableComponentUpdateProps = Omit<
  UseMutateProps<ConfigurableComponentDtoAjaxResponse, void, ConfigurableComponentDto>,
  'path' | 'verb'
>;

export const useConfigurableComponentUpdate = (props: UseConfigurableComponentUpdateProps) =>
  useMutate<ConfigurableComponentDtoAjaxResponse, AjaxResponseBase, void, ConfigurableComponentDto>(
    'PUT',
    `/api/services/ConfigurableComponents`,
    props
  );

export type ConfigurableComponentCreateProps = Omit<
  MutateProps<ConfigurableComponentDtoAjaxResponse, AjaxResponseBase, void, ConfigurableComponentDto>,
  'path' | 'verb'
>;

export const ConfigurableComponentCreate = (props: ConfigurableComponentCreateProps) => (
  <Mutate<ConfigurableComponentDtoAjaxResponse, AjaxResponseBase, void, ConfigurableComponentDto>
    verb="POST"
    path={`/api/services/ConfigurableComponents`}
    {...props}
  />
);

export type UseConfigurableComponentCreateProps = Omit<
  UseMutateProps<ConfigurableComponentDtoAjaxResponse, void, ConfigurableComponentDto>,
  'path' | 'verb'
>;

export const useConfigurableComponentCreate = (props: UseConfigurableComponentCreateProps) =>
  useMutate<ConfigurableComponentDtoAjaxResponse, AjaxResponseBase, void, ConfigurableComponentDto>(
    'POST',
    `/api/services/ConfigurableComponents`,
    props
  );

export type ConfigurableComponentUpdateSettingsProps = Omit<
  MutateProps<void, unknown, void, ConfigurableComponentUpdateSettingsInput>,
  'path' | 'verb'
> & { id: string };

export const ConfigurableComponentUpdateSettings = ({ id, ...props }: ConfigurableComponentUpdateSettingsProps) => (
  <Mutate<void, unknown, void, ConfigurableComponentUpdateSettingsInput>
    verb="PUT"
    path={`/api/services/ConfigurableComponents/${id}/Settings`}
    {...props}
  />
);

export type UseConfigurableComponentUpdateSettingsProps = Omit<
  UseMutateProps<void, void, ConfigurableComponentUpdateSettingsInput>,
  'path' | 'verb'
> & { id: string };

export const useConfigurableComponentUpdateSettings = ({ id, ...props }: UseConfigurableComponentUpdateSettingsProps) =>
  useMutate<void, unknown, void, ConfigurableComponentUpdateSettingsInput>(
    'PUT',
    `/api/services/ConfigurableComponents/${id}/Settings`,
    props
  );
