/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

import * as RestfulShesha from '../utils/fetchers';
export const SPEC_VERSION = 'v1';
/**
 * Indicate the source of the entity/property metadata
 */
export type MetadataSourceType = 1 | 2;

/**
 * Entity property DTO
 */
export interface EntityPropertyDto {
  id?: string;
  /**
   * Property Name
   */
  name?: string | null;
  /**
   * Label (display name)
   */
  label?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Data type
   */
  dataType?: string | null;
  /**
   * Data format
   */
  dataFormat?: string | null;
  /**
   * Entity type. Aplicable for entity references
   */
  entityType?: string | null;
  /**
   * Reference list name
   */
  referenceListName?: string | null;
  /**
   * Reference list namespace
   */
  referenceListNamespace?: string | null;
  source?: MetadataSourceType;
}

/**
 * Model configuration DTO
 */
export interface ModelConfigurationDto {
  id?: string;
  className?: string | null;
  namespace?: string | null;
  properties?: EntityPropertyDto[] | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface ModelConfigurationDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ModelConfigurationDto;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface ModelConfigurationsGetByNameQueryParams {
  name?: string | null;
  namespace?: string | null;
}

export type ModelConfigurationsGetByNameProps = Omit<
  GetProps<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, ModelConfigurationsGetByNameQueryParams, void>,
  'path'
>;

export const ModelConfigurationsGetByName = (props: ModelConfigurationsGetByNameProps) => (
  <Get<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, ModelConfigurationsGetByNameQueryParams, void>
    path={`/api/ModelConfigurations`}
    {...props}
  />
);

export type UseModelConfigurationsGetByNameProps = Omit<
  UseGetProps<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, ModelConfigurationsGetByNameQueryParams, void>,
  'path'
>;

export const useModelConfigurationsGetByName = (props: UseModelConfigurationsGetByNameProps) =>
  useGet<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, ModelConfigurationsGetByNameQueryParams, void>(
    `/api/ModelConfigurations`,
    props
  );

export type modelConfigurationsGetByNameProps = Omit<
  RestfulShesha.GetProps<
    ModelConfigurationDtoAjaxResponse,
    AjaxResponseBase,
    ModelConfigurationsGetByNameQueryParams,
    void
  >,
  'queryParams'
>;
export const modelConfigurationsGetByName = (
  queryParams: ModelConfigurationsGetByNameQueryParams,
  props: modelConfigurationsGetByNameProps
) =>
  RestfulShesha.get<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, ModelConfigurationsGetByNameQueryParams, void>(
    `/api/ModelConfigurations`,
    queryParams,
    props
  );

export type ModelConfigurationsUpdateProps = Omit<
  MutateProps<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationDto, void>,
  'path' | 'verb'
>;

export const ModelConfigurationsUpdate = (props: ModelConfigurationsUpdateProps) => (
  <Mutate<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationDto, void>
    verb="POST"
    path={`/api/ModelConfigurations`}
    {...props}
  />
);

export type UseModelConfigurationsUpdateProps = Omit<
  UseMutateProps<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationDto, void>,
  'path' | 'verb'
>;

export const useModelConfigurationsUpdate = (props: UseModelConfigurationsUpdateProps) =>
  useMutate<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationDto, void>(
    'POST',
    `/api/ModelConfigurations`,
    props
  );

export type modelConfigurationsUpdateProps = Omit<
  RestfulShesha.MutateProps<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationDto, void>,
  'data'
>;
export const modelConfigurationsUpdate = (data: ModelConfigurationDto, props: modelConfigurationsUpdateProps) =>
  RestfulShesha.mutate<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationDto, void>(
    'POST',
    `/api/ModelConfigurations`,
    data,
    props
  );

export interface ModelConfigurationsGetByIdPathParams {
  id: string;
}

export type ModelConfigurationsGetByIdProps = Omit<
  GetProps<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationsGetByIdPathParams>,
  'path'
> &
  ModelConfigurationsGetByIdPathParams;

export const ModelConfigurationsGetById = ({ id, ...props }: ModelConfigurationsGetByIdProps) => (
  <Get<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationsGetByIdPathParams>
    path={`/api/ModelConfigurations/${id}`}
    {...props}
  />
);

export type UseModelConfigurationsGetByIdProps = Omit<
  UseGetProps<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationsGetByIdPathParams>,
  'path'
> &
  ModelConfigurationsGetByIdPathParams;

export const useModelConfigurationsGetById = ({ id, ...props }: UseModelConfigurationsGetByIdProps) =>
  useGet<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationsGetByIdPathParams>(
    (paramsInPath: ModelConfigurationsGetByIdPathParams) => `/api/ModelConfigurations/${paramsInPath.id}`,
    { pathParams: { id }, ...props }
  );

export type modelConfigurationsGetByIdProps = Omit<
  RestfulShesha.GetProps<
    ModelConfigurationDtoAjaxResponse,
    AjaxResponseBase,
    void,
    ModelConfigurationsGetByIdPathParams
  > & { id: string },
  'queryParams'
>;
export const modelConfigurationsGetById = ({ id, ...props }: modelConfigurationsGetByIdProps) =>
  RestfulShesha.get<ModelConfigurationDtoAjaxResponse, AjaxResponseBase, void, ModelConfigurationsGetByIdPathParams>(
    `/api/ModelConfigurations/${id}`,
    undefined,
    props
  );
