/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

/**
 * Generic entity Dto with display text
 */
export interface GuidEntityWithDisplayNameDto {
  id?: string;
  /**
   * Entity display name
   */
  displayText?: string | null;
}

export interface NoteDto {
  id?: string;
  /**
   * Id of the owner entity
   */
  ownerId: string;
  /**
   * Type short alias of the owner entity
   */
  ownerType: string;
  /**
   * Creation time
   */
  creationTime?: string | null;
  /**
   * Category of the note. Is used to split notes into groups
   */
  category?: number | null;
  /**
   * Note importance (priority)
   */
  priority?: number | null;
  /**
   * Id of the parent note
   */
  parentId?: string | null;
  /**
   * Text
   */
  noteText: string;
  author?: GuidEntityWithDisplayNameDto;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface NoteDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: NoteDto[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface CreateNoteDto {
  id?: string;
  /**
   * Id of the owner entity
   */
  ownerId: string;
  /**
   * Type short alias of the owner entity
   */
  ownerType: string;
  /**
   * Category of the note. Is used to split notes into groups
   */
  category?: number | null;
  /**
   * Note importance (priority)
   */
  priority?: number | null;
  /**
   * Id of the parent note
   */
  parentId?: string | null;
  /**
   * Text
   */
  noteText: string;
}

export interface NoteDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: NoteDto;
}

export interface NoteDtoPagedResultDto {
  items?: NoteDto[] | null;
  totalCount?: number;
}

export interface NoteDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: NoteDtoPagedResultDto;
}

export interface UpdateNoteDto {
  id?: string;
  /**
   * Category of the note. Is used to split notes into groups
   */
  category?: number | null;
  /**
   * Note importance (priority)
   */
  priority?: number | null;
  /**
   * Id of the parent note
   */
  parentId?: string | null;
  /**
   * Text
   */
  noteText: string;
}

export interface NoteGetListQueryParams {
  /**
   * Id of the owner entity
   */
  ownerId: string;
  /**
   * Type short alias of the owner entity
   */
  ownerType: string;
  /**
   * Category of the note. Is used to split notes into groups
   */
  category?: number | null;
  /**
   * Set to true to get notes of all categories
   */
  allCategories?: boolean;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type NoteGetListProps = Omit<
  GetProps<NoteDtoListAjaxResponse, AjaxResponseBase, NoteGetListQueryParams>,
  'path'
>;

export const NoteGetList = (props: NoteGetListProps) => (
  <Get<NoteDtoListAjaxResponse, AjaxResponseBase, NoteGetListQueryParams>
    path={`/api/services/app/Note/GetList`}
    {...props}
  />
);

export type UseNoteGetListProps = Omit<UseGetProps<NoteDtoListAjaxResponse, NoteGetListQueryParams>, 'path'>;

export const useNoteGetList = (props: UseNoteGetListProps) =>
  useGet<NoteDtoListAjaxResponse, AjaxResponseBase, NoteGetListQueryParams>(`/api/services/app/Note/GetList`, props);

export interface NoteCreateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type NoteCreateProps = Omit<
  MutateProps<NoteDtoAjaxResponse, AjaxResponseBase, NoteCreateQueryParams, CreateNoteDto>,
  'path' | 'verb'
>;

export const NoteCreate = (props: NoteCreateProps) => (
  <Mutate<NoteDtoAjaxResponse, AjaxResponseBase, NoteCreateQueryParams, CreateNoteDto>
    verb="POST"
    path={`/api/services/app/Note/Create`}
    {...props}
  />
);

export type UseNoteCreateProps = Omit<
  UseMutateProps<NoteDtoAjaxResponse, NoteCreateQueryParams, CreateNoteDto>,
  'path' | 'verb'
>;

export const useNoteCreate = (props: UseNoteCreateProps) =>
  useMutate<NoteDtoAjaxResponse, AjaxResponseBase, NoteCreateQueryParams, CreateNoteDto>(
    'POST',
    `/api/services/app/Note/Create`,
    props
  );

export interface NoteGetQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type NoteGetProps = Omit<GetProps<NoteDtoAjaxResponse, AjaxResponseBase, NoteGetQueryParams>, 'path'>;

export const NoteGet = (props: NoteGetProps) => (
  <Get<NoteDtoAjaxResponse, AjaxResponseBase, NoteGetQueryParams> path={`/api/services/app/Note/Get`} {...props} />
);

export type UseNoteGetProps = Omit<UseGetProps<NoteDtoAjaxResponse, NoteGetQueryParams>, 'path'>;

export const useNoteGet = (props: UseNoteGetProps) =>
  useGet<NoteDtoAjaxResponse, AjaxResponseBase, NoteGetQueryParams>(`/api/services/app/Note/Get`, props);

export interface NoteGetAllQueryParams {
  keyword?: string | null;
  skipCount?: number;
  maxResultCount?: number;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type NoteGetAllProps = Omit<
  GetProps<NoteDtoPagedResultDtoAjaxResponse, AjaxResponseBase, NoteGetAllQueryParams>,
  'path'
>;

export const NoteGetAll = (props: NoteGetAllProps) => (
  <Get<NoteDtoPagedResultDtoAjaxResponse, AjaxResponseBase, NoteGetAllQueryParams>
    path={`/api/services/app/Note/GetAll`}
    {...props}
  />
);

export type UseNoteGetAllProps = Omit<UseGetProps<NoteDtoPagedResultDtoAjaxResponse, NoteGetAllQueryParams>, 'path'>;

export const useNoteGetAll = (props: UseNoteGetAllProps) =>
  useGet<NoteDtoPagedResultDtoAjaxResponse, AjaxResponseBase, NoteGetAllQueryParams>(
    `/api/services/app/Note/GetAll`,
    props
  );

export interface NoteUpdateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type NoteUpdateProps = Omit<
  MutateProps<NoteDtoAjaxResponse, AjaxResponseBase, NoteUpdateQueryParams, UpdateNoteDto>,
  'path' | 'verb'
>;

export const NoteUpdate = (props: NoteUpdateProps) => (
  <Mutate<NoteDtoAjaxResponse, AjaxResponseBase, NoteUpdateQueryParams, UpdateNoteDto>
    verb="PUT"
    path={`/api/services/app/Note/Update`}
    {...props}
  />
);

export type UseNoteUpdateProps = Omit<
  UseMutateProps<NoteDtoAjaxResponse, NoteUpdateQueryParams, UpdateNoteDto>,
  'path' | 'verb'
>;

export const useNoteUpdate = (props: UseNoteUpdateProps) =>
  useMutate<NoteDtoAjaxResponse, AjaxResponseBase, NoteUpdateQueryParams, UpdateNoteDto>(
    'PUT',
    `/api/services/app/Note/Update`,
    props
  );

export interface NoteDeleteQueryParams {
  id?: string;
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type NoteDeleteProps = Omit<MutateProps<void, unknown, NoteDeleteQueryParams, void>, 'path' | 'verb'>;

export const NoteDelete = (props: NoteDeleteProps) => (
  <Mutate<void, unknown, NoteDeleteQueryParams, void> verb="DELETE" path={`/api/services/app/Note/Delete`} {...props} />
);

export type UseNoteDeleteProps = Omit<UseMutateProps<void, NoteDeleteQueryParams, void>, 'path' | 'verb'>;

export const useNoteDelete = (props: UseNoteDeleteProps) =>
  useMutate<void, unknown, NoteDeleteQueryParams, void>('DELETE', `/api/services/app/Note/Delete`, props);
