/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

import * as RestfulShesha from '../utils/fetchers';
export const SPEC_VERSION = 'v1';
/**
 * Generic entity Dto with display text
 */
export interface GuidEntityWithDisplayNameDto {
  id?: string;
  /**
   * Entity display name
   */
  displayText?: string | null;
}

export interface NoteDto {
  id?: string;
  /**
   * Id of the owner entity
   */
  ownerId: string;
  /**
   * Type short alias of the owner entity
   */
  ownerType: string;
  /**
   * Creation time
   */
  creationTime?: string | null;
  /**
   * Category of the note. Is used to split notes into groups
   */
  category?: number | null;
  /**
   * Note importance (priority)
   */
  priority?: number | null;
  /**
   * Id of the parent note
   */
  parentId?: string | null;
  /**
   * Text
   */
  noteText: string;
  author?: GuidEntityWithDisplayNameDto;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface NoteDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: NoteDto[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface CreateNoteDto {
  id?: string;
  /**
   * Id of the owner entity
   */
  ownerId: string;
  /**
   * Type short alias of the owner entity
   */
  ownerType: string;
  /**
   * Category of the note. Is used to split notes into groups
   */
  category?: number | null;
  /**
   * Note importance (priority)
   */
  priority?: number | null;
  /**
   * Id of the parent note
   */
  parentId?: string | null;
  /**
   * Text
   */
  noteText: string;
}

export interface NoteDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: NoteDto;
}

export interface NoteDtoPagedResultDto {
  items?: NoteDto[] | null;
  totalCount?: number;
}

export interface NoteDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: NoteDtoPagedResultDto;
}

export interface UpdateNoteDto {
  id?: string;
  /**
   * Category of the note. Is used to split notes into groups
   */
  category?: number | null;
  /**
   * Note importance (priority)
   */
  priority?: number | null;
  /**
   * Id of the parent note
   */
  parentId?: string | null;
  /**
   * Text
   */
  noteText: string;
}

export interface NoteGetListQueryParams {
  /**
   * Id of the owner entity
   */
  ownerId: string;
  /**
   * Type short alias of the owner entity
   */
  ownerType: string;
  /**
   * Category of the note. Is used to split notes into groups
   */
  category?: number | null;
  /**
   * Set to true to get notes of all categories
   */
  allCategories?: boolean;
}

export type NoteGetListProps = Omit<
  GetProps<NoteDtoListAjaxResponse, AjaxResponseBase, NoteGetListQueryParams, void>,
  'path'
>;

export const NoteGetList = (props: NoteGetListProps) => (
  <Get<NoteDtoListAjaxResponse, AjaxResponseBase, NoteGetListQueryParams, void>
    path={`/api/services/app/Note/GetList`}
    {...props}
  />
);

export type UseNoteGetListProps = Omit<
  UseGetProps<NoteDtoListAjaxResponse, AjaxResponseBase, NoteGetListQueryParams, void>,
  'path'
>;

export const useNoteGetList = (props: UseNoteGetListProps) =>
  useGet<NoteDtoListAjaxResponse, AjaxResponseBase, NoteGetListQueryParams, void>(
    `/api/services/app/Note/GetList`,
    props
  );

export type noteGetListProps = Omit<
  RestfulShesha.GetProps<NoteDtoListAjaxResponse, AjaxResponseBase, NoteGetListQueryParams, void>,
  'queryParams'
>;
export const noteGetList = (queryParams: NoteGetListQueryParams, props: noteGetListProps) =>
  RestfulShesha.get<NoteDtoListAjaxResponse, AjaxResponseBase, NoteGetListQueryParams, void>(
    `/api/services/app/Note/GetList`,
    queryParams,
    props
  );

export type NoteCreateProps = Omit<
  MutateProps<NoteDtoAjaxResponse, AjaxResponseBase, void, CreateNoteDto, void>,
  'path' | 'verb'
>;

export const NoteCreate = (props: NoteCreateProps) => (
  <Mutate<NoteDtoAjaxResponse, AjaxResponseBase, void, CreateNoteDto, void>
    verb="POST"
    path={`/api/services/app/Note/Create`}
    {...props}
  />
);

export type UseNoteCreateProps = Omit<
  UseMutateProps<NoteDtoAjaxResponse, AjaxResponseBase, void, CreateNoteDto, void>,
  'path' | 'verb'
>;

export const useNoteCreate = (props: UseNoteCreateProps) =>
  useMutate<NoteDtoAjaxResponse, AjaxResponseBase, void, CreateNoteDto, void>(
    'POST',
    `/api/services/app/Note/Create`,
    props
  );

export type noteCreateProps = Omit<
  RestfulShesha.MutateProps<NoteDtoAjaxResponse, AjaxResponseBase, void, CreateNoteDto, void>,
  'data'
>;
export const noteCreate = (data: CreateNoteDto, props: noteCreateProps) =>
  RestfulShesha.mutate<NoteDtoAjaxResponse, AjaxResponseBase, void, CreateNoteDto, void>(
    'POST',
    `/api/services/app/Note/Create`,
    data,
    props
  );

export interface NoteGetQueryParams {
  id?: string;
}

export type NoteGetProps = Omit<GetProps<NoteDtoAjaxResponse, AjaxResponseBase, NoteGetQueryParams, void>, 'path'>;

export const NoteGet = (props: NoteGetProps) => (
  <Get<NoteDtoAjaxResponse, AjaxResponseBase, NoteGetQueryParams, void>
    path={`/api/services/app/Note/Get`}
    {...props}
  />
);

export type UseNoteGetProps = Omit<
  UseGetProps<NoteDtoAjaxResponse, AjaxResponseBase, NoteGetQueryParams, void>,
  'path'
>;

export const useNoteGet = (props: UseNoteGetProps) =>
  useGet<NoteDtoAjaxResponse, AjaxResponseBase, NoteGetQueryParams, void>(`/api/services/app/Note/Get`, props);

export type noteGetProps = Omit<
  RestfulShesha.GetProps<NoteDtoAjaxResponse, AjaxResponseBase, NoteGetQueryParams, void>,
  'queryParams'
>;
export const noteGet = (queryParams: NoteGetQueryParams, props: noteGetProps) =>
  RestfulShesha.get<NoteDtoAjaxResponse, AjaxResponseBase, NoteGetQueryParams, void>(
    `/api/services/app/Note/Get`,
    queryParams,
    props
  );

export interface NoteGetAllQueryParams {
  keyword?: string | null;
  skipCount?: number;
  maxResultCount?: number;
}

export type NoteGetAllProps = Omit<
  GetProps<NoteDtoPagedResultDtoAjaxResponse, AjaxResponseBase, NoteGetAllQueryParams, void>,
  'path'
>;

export const NoteGetAll = (props: NoteGetAllProps) => (
  <Get<NoteDtoPagedResultDtoAjaxResponse, AjaxResponseBase, NoteGetAllQueryParams, void>
    path={`/api/services/app/Note/GetAll`}
    {...props}
  />
);

export type UseNoteGetAllProps = Omit<
  UseGetProps<NoteDtoPagedResultDtoAjaxResponse, AjaxResponseBase, NoteGetAllQueryParams, void>,
  'path'
>;

export const useNoteGetAll = (props: UseNoteGetAllProps) =>
  useGet<NoteDtoPagedResultDtoAjaxResponse, AjaxResponseBase, NoteGetAllQueryParams, void>(
    `/api/services/app/Note/GetAll`,
    props
  );

export type noteGetAllProps = Omit<
  RestfulShesha.GetProps<NoteDtoPagedResultDtoAjaxResponse, AjaxResponseBase, NoteGetAllQueryParams, void>,
  'queryParams'
>;
export const noteGetAll = (queryParams: NoteGetAllQueryParams, props: noteGetAllProps) =>
  RestfulShesha.get<NoteDtoPagedResultDtoAjaxResponse, AjaxResponseBase, NoteGetAllQueryParams, void>(
    `/api/services/app/Note/GetAll`,
    queryParams,
    props
  );

export type NoteUpdateProps = Omit<
  MutateProps<NoteDtoAjaxResponse, AjaxResponseBase, void, UpdateNoteDto, void>,
  'path' | 'verb'
>;

export const NoteUpdate = (props: NoteUpdateProps) => (
  <Mutate<NoteDtoAjaxResponse, AjaxResponseBase, void, UpdateNoteDto, void>
    verb="PUT"
    path={`/api/services/app/Note/Update`}
    {...props}
  />
);

export type UseNoteUpdateProps = Omit<
  UseMutateProps<NoteDtoAjaxResponse, AjaxResponseBase, void, UpdateNoteDto, void>,
  'path' | 'verb'
>;

export const useNoteUpdate = (props: UseNoteUpdateProps) =>
  useMutate<NoteDtoAjaxResponse, AjaxResponseBase, void, UpdateNoteDto, void>(
    'PUT',
    `/api/services/app/Note/Update`,
    props
  );

export type noteUpdateProps = Omit<
  RestfulShesha.MutateProps<NoteDtoAjaxResponse, AjaxResponseBase, void, UpdateNoteDto, void>,
  'data'
>;
export const noteUpdate = (data: UpdateNoteDto, props: noteUpdateProps) =>
  RestfulShesha.mutate<NoteDtoAjaxResponse, AjaxResponseBase, void, UpdateNoteDto, void>(
    'PUT',
    `/api/services/app/Note/Update`,
    data,
    props
  );

export interface NoteDeleteQueryParams {
  id?: string;
}

export type NoteDeleteProps = Omit<MutateProps<void, unknown, NoteDeleteQueryParams, void, void>, 'path' | 'verb'>;

export const NoteDelete = (props: NoteDeleteProps) => (
  <Mutate<void, unknown, NoteDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/app/Note/Delete`}
    {...props}
  />
);

export type UseNoteDeleteProps = Omit<
  UseMutateProps<void, unknown, NoteDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useNoteDelete = (props: UseNoteDeleteProps) =>
  useMutate<void, unknown, NoteDeleteQueryParams, void, void>('DELETE', `/api/services/app/Note/Delete`, { ...props });

export type noteDeleteProps = Omit<RestfulShesha.MutateProps<void, unknown, NoteDeleteQueryParams, void, void>, 'data'>;
export const noteDelete = (props: noteDeleteProps) =>
  RestfulShesha.mutate<void, unknown, NoteDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/app/Note/Delete`,
    undefined,
    props
  );
