/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

import * as RestfulShesha from '../utils/fetchers';
export const SPEC_VERSION = 'v1';
/**
 * Generic entity Dto with display text
 */
export interface GuidNullableEntityWithDisplayNameDto {
  id?: string | null;
  /**
   * Entity display name
   */
  displayText?: string | null;
}

/**
 * Dto of the Shesha.Domain.ReferenceListItem
 */
export interface ReferenceListItemDto {
  id?: string;
  item?: string | null;
  itemValue?: number;
  description?: string | null;
  orderIndex?: number;
  referenceList?: GuidNullableEntityWithDisplayNameDto;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface ReferenceListItemDtoListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ReferenceListItemDto[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

/**
 * Dto of the Shesha.Domain.ReferenceList
 */
export interface ReferenceListDto {
  id?: string;
  name?: string | null;
  description?: string | null;
  hardLinkToApplication?: boolean;
  namespace?: string | null;
  noSelectionValue?: number | null;
}

export interface ReferenceListDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ReferenceListDto;
}

export interface ReferenceListDtoPagedResultDto {
  items?: ReferenceListDto[] | null;
  totalCount?: number;
}

export interface ReferenceListDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ReferenceListDtoPagedResultDto;
}

export interface ReferenceListGetItemsQueryParams {
  namespace?: string | null;
  name?: string | null;
}

export type ReferenceListGetItemsProps = Omit<
  GetProps<ReferenceListItemDtoListAjaxResponse, AjaxResponseBase, ReferenceListGetItemsQueryParams, void>,
  'path'
>;

/**
 * Get ReferenceList Items
 */
export const ReferenceListGetItems = (props: ReferenceListGetItemsProps) => (
  <Get<ReferenceListItemDtoListAjaxResponse, AjaxResponseBase, ReferenceListGetItemsQueryParams, void>
    path={`/api/services/app/ReferenceList/GetItems`}
    {...props}
  />
);

export type UseReferenceListGetItemsProps = Omit<
  UseGetProps<ReferenceListItemDtoListAjaxResponse, AjaxResponseBase, ReferenceListGetItemsQueryParams, void>,
  'path'
>;

/**
 * Get ReferenceList Items
 */
export const useReferenceListGetItems = (props: UseReferenceListGetItemsProps) =>
  useGet<ReferenceListItemDtoListAjaxResponse, AjaxResponseBase, ReferenceListGetItemsQueryParams, void>(
    `/api/services/app/ReferenceList/GetItems`,
    props
  );

export type referenceListGetItemsProps = Omit<
  RestfulShesha.GetProps<
    ReferenceListItemDtoListAjaxResponse,
    AjaxResponseBase,
    ReferenceListGetItemsQueryParams,
    void
  >,
  'queryParams'
>;
/**
 * Get ReferenceList Items
 */
export const referenceListGetItems = (
  queryParams: ReferenceListGetItemsQueryParams,
  props: referenceListGetItemsProps
) =>
  RestfulShesha.get<ReferenceListItemDtoListAjaxResponse, AjaxResponseBase, ReferenceListGetItemsQueryParams, void>(
    `/api/services/app/ReferenceList/GetItems`,
    queryParams,
    props
  );

export interface ReferenceListGetQueryParams {
  id?: string;
}

export type ReferenceListGetProps = Omit<
  GetProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>,
  'path'
>;

export const ReferenceListGet = (props: ReferenceListGetProps) => (
  <Get<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>
    path={`/api/services/app/ReferenceList/Get`}
    {...props}
  />
);

export type UseReferenceListGetProps = Omit<
  UseGetProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>,
  'path'
>;

export const useReferenceListGet = (props: UseReferenceListGetProps) =>
  useGet<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>(
    `/api/services/app/ReferenceList/Get`,
    props
  );

export type referenceListGetProps = Omit<
  RestfulShesha.GetProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>,
  'queryParams'
>;
export const referenceListGet = (queryParams: ReferenceListGetQueryParams, props: referenceListGetProps) =>
  RestfulShesha.get<ReferenceListDtoAjaxResponse, AjaxResponseBase, ReferenceListGetQueryParams, void>(
    `/api/services/app/ReferenceList/Get`,
    queryParams,
    props
  );

export interface ReferenceListGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
}

export type ReferenceListGetAllProps = Omit<
  GetProps<ReferenceListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, ReferenceListGetAllQueryParams, void>,
  'path'
>;

export const ReferenceListGetAll = (props: ReferenceListGetAllProps) => (
  <Get<ReferenceListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, ReferenceListGetAllQueryParams, void>
    path={`/api/services/app/ReferenceList/GetAll`}
    {...props}
  />
);

export type UseReferenceListGetAllProps = Omit<
  UseGetProps<ReferenceListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, ReferenceListGetAllQueryParams, void>,
  'path'
>;

export const useReferenceListGetAll = (props: UseReferenceListGetAllProps) =>
  useGet<ReferenceListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, ReferenceListGetAllQueryParams, void>(
    `/api/services/app/ReferenceList/GetAll`,
    props
  );

export type referenceListGetAllProps = Omit<
  RestfulShesha.GetProps<
    ReferenceListDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ReferenceListGetAllQueryParams,
    void
  >,
  'queryParams'
>;
export const referenceListGetAll = (queryParams: ReferenceListGetAllQueryParams, props: referenceListGetAllProps) =>
  RestfulShesha.get<ReferenceListDtoPagedResultDtoAjaxResponse, AjaxResponseBase, ReferenceListGetAllQueryParams, void>(
    `/api/services/app/ReferenceList/GetAll`,
    queryParams,
    props
  );

export type ReferenceListCreateProps = Omit<
  MutateProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>,
  'path' | 'verb'
>;

export const ReferenceListCreate = (props: ReferenceListCreateProps) => (
  <Mutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>
    verb="POST"
    path={`/api/services/app/ReferenceList/Create`}
    {...props}
  />
);

export type UseReferenceListCreateProps = Omit<
  UseMutateProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>,
  'path' | 'verb'
>;

export const useReferenceListCreate = (props: UseReferenceListCreateProps) =>
  useMutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>(
    'POST',
    `/api/services/app/ReferenceList/Create`,
    props
  );

export type referenceListCreateProps = Omit<
  RestfulShesha.MutateProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>,
  'data'
>;
export const referenceListCreate = (data: ReferenceListDto, props: referenceListCreateProps) =>
  RestfulShesha.mutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>(
    'POST',
    `/api/services/app/ReferenceList/Create`,
    data,
    props
  );

export type ReferenceListUpdateProps = Omit<
  MutateProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>,
  'path' | 'verb'
>;

export const ReferenceListUpdate = (props: ReferenceListUpdateProps) => (
  <Mutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>
    verb="PUT"
    path={`/api/services/app/ReferenceList/Update`}
    {...props}
  />
);

export type UseReferenceListUpdateProps = Omit<
  UseMutateProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>,
  'path' | 'verb'
>;

export const useReferenceListUpdate = (props: UseReferenceListUpdateProps) =>
  useMutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>(
    'PUT',
    `/api/services/app/ReferenceList/Update`,
    props
  );

export type referenceListUpdateProps = Omit<
  RestfulShesha.MutateProps<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>,
  'data'
>;
export const referenceListUpdate = (data: ReferenceListDto, props: referenceListUpdateProps) =>
  RestfulShesha.mutate<ReferenceListDtoAjaxResponse, AjaxResponseBase, void, ReferenceListDto, void>(
    'PUT',
    `/api/services/app/ReferenceList/Update`,
    data,
    props
  );

export interface ReferenceListDeleteQueryParams {
  id?: string;
}

export type ReferenceListDeleteProps = Omit<
  MutateProps<void, unknown, ReferenceListDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const ReferenceListDelete = (props: ReferenceListDeleteProps) => (
  <Mutate<void, unknown, ReferenceListDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/app/ReferenceList/Delete`}
    {...props}
  />
);

export type UseReferenceListDeleteProps = Omit<
  UseMutateProps<void, unknown, ReferenceListDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useReferenceListDelete = (props: UseReferenceListDeleteProps) =>
  useMutate<void, unknown, ReferenceListDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/app/ReferenceList/Delete`,
    { ...props }
  );

export type referenceListDeleteProps = Omit<
  RestfulShesha.MutateProps<void, unknown, ReferenceListDeleteQueryParams, void, void>,
  'data'
>;
export const referenceListDelete = (props: referenceListDeleteProps) =>
  RestfulShesha.mutate<void, unknown, ReferenceListDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/app/ReferenceList/Delete`,
    undefined,
    props
  );
