/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

import * as RestfulShesha from '../utils/fetchers';
export const SPEC_VERSION = 'v1';
/**
 * Represents event log item logged by Shesha.Scheduler.SignalR.SignalrAppender
 */
export interface EventLogItem {
  /**
   * Logged message
   */
  message?: string | null;
  /**
   * Event timestamp
   */
  timeStamp?: string;
  /**
   * Level (info/warn/error)
   */
  level?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface EventLogItemListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: EventLogItem[] | null;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface FileStreamResultAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: string | null;
}

/**
 * Generic entity Dto with display text
 */
export interface Int64NullableEntityWithDisplayNameDto {
  id?: number | null;
  /**
   * Entity display name
   */
  displayText?: string | null;
}

/**
 * Generic entity Dto with display text
 */
export interface GuidNullableEntityWithDisplayNameDto {
  id?: string | null;
  /**
   * Entity display name
   */
  displayText?: string | null;
}

export interface ReferenceListItemValueDto {
  item?: string | null;
  itemValue?: number | null;
}

export interface ScheduledJobExecutionDto {
  id?: string;
  /**
   * Datetime of the execution start
   */
  startedOn?: string | null;
  /**
   * Datetime of the execution finish
   */
  finishedOn?: string | null;
  startedBy?: Int64NullableEntityWithDisplayNameDto;
  job?: GuidNullableEntityWithDisplayNameDto;
  trigger?: GuidNullableEntityWithDisplayNameDto;
  /**
   * Error message
   */
  errorMessage?: string | null;
  status?: ReferenceListItemValueDto;
}

export interface ScheduledJobExecutionDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ScheduledJobExecutionDto;
}

export interface ScheduledJobExecutionDtoPagedResultDto {
  items?: ScheduledJobExecutionDto[] | null;
  totalCount?: number;
}

export interface ScheduledJobExecutionDtoPagedResultDtoAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ScheduledJobExecutionDtoPagedResultDto;
}

export interface ScheduledJobExecutionGetEventLogItemsQueryParams {
  id?: string;
}

export type ScheduledJobExecutionGetEventLogItemsProps = Omit<
  GetProps<EventLogItemListAjaxResponse, AjaxResponseBase, ScheduledJobExecutionGetEventLogItemsQueryParams, void>,
  'path'
>;

/**
 * Get event log items for the specified job execution
 */
export const ScheduledJobExecutionGetEventLogItems = (props: ScheduledJobExecutionGetEventLogItemsProps) => (
  <Get<EventLogItemListAjaxResponse, AjaxResponseBase, ScheduledJobExecutionGetEventLogItemsQueryParams, void>
    path={`/api/services/Scheduler/ScheduledJobExecution/GetEventLogItems`}
    {...props}
  />
);

export type UseScheduledJobExecutionGetEventLogItemsProps = Omit<
  UseGetProps<EventLogItemListAjaxResponse, AjaxResponseBase, ScheduledJobExecutionGetEventLogItemsQueryParams, void>,
  'path'
>;

/**
 * Get event log items for the specified job execution
 */
export const useScheduledJobExecutionGetEventLogItems = (props: UseScheduledJobExecutionGetEventLogItemsProps) =>
  useGet<EventLogItemListAjaxResponse, AjaxResponseBase, ScheduledJobExecutionGetEventLogItemsQueryParams, void>(
    `/api/services/Scheduler/ScheduledJobExecution/GetEventLogItems`,
    props
  );

export type scheduledJobExecutionGetEventLogItemsProps = Omit<
  RestfulShesha.GetProps<
    EventLogItemListAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionGetEventLogItemsQueryParams,
    void
  >,
  'queryParams'
>;
/**
 * Get event log items for the specified job execution
 */
export const scheduledJobExecutionGetEventLogItems = (
  queryParams: ScheduledJobExecutionGetEventLogItemsQueryParams,
  props: scheduledJobExecutionGetEventLogItemsProps
) =>
  RestfulShesha.get<
    EventLogItemListAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionGetEventLogItemsQueryParams,
    void
  >(`/api/services/Scheduler/ScheduledJobExecution/GetEventLogItems`, queryParams, props);

export interface ScheduledJobExecutionDownloadLogFileQueryParams {
  /**
   * Id of the scheduled job execution
   */
  id?: string;
}

export type ScheduledJobExecutionDownloadLogFileProps = Omit<
  GetProps<FileStreamResultAjaxResponse, AjaxResponseBase, ScheduledJobExecutionDownloadLogFileQueryParams, void>,
  'path'
>;

/**
 * Download log file of the job execution
 */
export const ScheduledJobExecutionDownloadLogFile = (props: ScheduledJobExecutionDownloadLogFileProps) => (
  <Get<FileStreamResultAjaxResponse, AjaxResponseBase, ScheduledJobExecutionDownloadLogFileQueryParams, void>
    path={`/api/services/Scheduler/ScheduledJobExecution/DownloadLogFile`}
    {...props}
  />
);

export type UseScheduledJobExecutionDownloadLogFileProps = Omit<
  UseGetProps<FileStreamResultAjaxResponse, AjaxResponseBase, ScheduledJobExecutionDownloadLogFileQueryParams, void>,
  'path'
>;

/**
 * Download log file of the job execution
 */
export const useScheduledJobExecutionDownloadLogFile = (props: UseScheduledJobExecutionDownloadLogFileProps) =>
  useGet<FileStreamResultAjaxResponse, AjaxResponseBase, ScheduledJobExecutionDownloadLogFileQueryParams, void>(
    `/api/services/Scheduler/ScheduledJobExecution/DownloadLogFile`,
    props
  );

export type scheduledJobExecutionDownloadLogFileProps = Omit<
  RestfulShesha.GetProps<
    FileStreamResultAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionDownloadLogFileQueryParams,
    void
  >,
  'queryParams'
>;
/**
 * Download log file of the job execution
 */
export const scheduledJobExecutionDownloadLogFile = (
  queryParams: ScheduledJobExecutionDownloadLogFileQueryParams,
  props: scheduledJobExecutionDownloadLogFileProps
) =>
  RestfulShesha.get<
    FileStreamResultAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionDownloadLogFileQueryParams,
    void
  >(`/api/services/Scheduler/ScheduledJobExecution/DownloadLogFile`, queryParams, props);

export interface ScheduledJobExecutionGetQueryParams {
  id?: string;
}

export type ScheduledJobExecutionGetProps = Omit<
  GetProps<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, ScheduledJobExecutionGetQueryParams, void>,
  'path'
>;

export const ScheduledJobExecutionGet = (props: ScheduledJobExecutionGetProps) => (
  <Get<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, ScheduledJobExecutionGetQueryParams, void>
    path={`/api/services/Scheduler/ScheduledJobExecution/Get`}
    {...props}
  />
);

export type UseScheduledJobExecutionGetProps = Omit<
  UseGetProps<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, ScheduledJobExecutionGetQueryParams, void>,
  'path'
>;

export const useScheduledJobExecutionGet = (props: UseScheduledJobExecutionGetProps) =>
  useGet<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, ScheduledJobExecutionGetQueryParams, void>(
    `/api/services/Scheduler/ScheduledJobExecution/Get`,
    props
  );

export type scheduledJobExecutionGetProps = Omit<
  RestfulShesha.GetProps<
    ScheduledJobExecutionDtoAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionGetQueryParams,
    void
  >,
  'queryParams'
>;
export const scheduledJobExecutionGet = (
  queryParams: ScheduledJobExecutionGetQueryParams,
  props: scheduledJobExecutionGetProps
) =>
  RestfulShesha.get<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, ScheduledJobExecutionGetQueryParams, void>(
    `/api/services/Scheduler/ScheduledJobExecution/Get`,
    queryParams,
    props
  );

export interface ScheduledJobExecutionGetAllQueryParams {
  sorting?: string | null;
  skipCount?: number;
  maxResultCount?: number;
}

export type ScheduledJobExecutionGetAllProps = Omit<
  GetProps<
    ScheduledJobExecutionDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionGetAllQueryParams,
    void
  >,
  'path'
>;

export const ScheduledJobExecutionGetAll = (props: ScheduledJobExecutionGetAllProps) => (
  <Get<
    ScheduledJobExecutionDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionGetAllQueryParams,
    void
  >
    path={`/api/services/Scheduler/ScheduledJobExecution/GetAll`}
    {...props}
  />
);

export type UseScheduledJobExecutionGetAllProps = Omit<
  UseGetProps<
    ScheduledJobExecutionDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionGetAllQueryParams,
    void
  >,
  'path'
>;

export const useScheduledJobExecutionGetAll = (props: UseScheduledJobExecutionGetAllProps) =>
  useGet<
    ScheduledJobExecutionDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionGetAllQueryParams,
    void
  >(`/api/services/Scheduler/ScheduledJobExecution/GetAll`, props);

export type scheduledJobExecutionGetAllProps = Omit<
  RestfulShesha.GetProps<
    ScheduledJobExecutionDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionGetAllQueryParams,
    void
  >,
  'queryParams'
>;
export const scheduledJobExecutionGetAll = (
  queryParams: ScheduledJobExecutionGetAllQueryParams,
  props: scheduledJobExecutionGetAllProps
) =>
  RestfulShesha.get<
    ScheduledJobExecutionDtoPagedResultDtoAjaxResponse,
    AjaxResponseBase,
    ScheduledJobExecutionGetAllQueryParams,
    void
  >(`/api/services/Scheduler/ScheduledJobExecution/GetAll`, queryParams, props);

export type ScheduledJobExecutionCreateProps = Omit<
  MutateProps<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>,
  'path' | 'verb'
>;

export const ScheduledJobExecutionCreate = (props: ScheduledJobExecutionCreateProps) => (
  <Mutate<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>
    verb="POST"
    path={`/api/services/Scheduler/ScheduledJobExecution/Create`}
    {...props}
  />
);

export type UseScheduledJobExecutionCreateProps = Omit<
  UseMutateProps<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>,
  'path' | 'verb'
>;

export const useScheduledJobExecutionCreate = (props: UseScheduledJobExecutionCreateProps) =>
  useMutate<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>(
    'POST',
    `/api/services/Scheduler/ScheduledJobExecution/Create`,
    props
  );

export type scheduledJobExecutionCreateProps = Omit<
  RestfulShesha.MutateProps<
    ScheduledJobExecutionDtoAjaxResponse,
    AjaxResponseBase,
    void,
    ScheduledJobExecutionDto,
    void
  >,
  'data'
>;
export const scheduledJobExecutionCreate = (data: ScheduledJobExecutionDto, props: scheduledJobExecutionCreateProps) =>
  RestfulShesha.mutate<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>(
    'POST',
    `/api/services/Scheduler/ScheduledJobExecution/Create`,
    data,
    props
  );

export type ScheduledJobExecutionUpdateProps = Omit<
  MutateProps<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>,
  'path' | 'verb'
>;

export const ScheduledJobExecutionUpdate = (props: ScheduledJobExecutionUpdateProps) => (
  <Mutate<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>
    verb="PUT"
    path={`/api/services/Scheduler/ScheduledJobExecution/Update`}
    {...props}
  />
);

export type UseScheduledJobExecutionUpdateProps = Omit<
  UseMutateProps<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>,
  'path' | 'verb'
>;

export const useScheduledJobExecutionUpdate = (props: UseScheduledJobExecutionUpdateProps) =>
  useMutate<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>(
    'PUT',
    `/api/services/Scheduler/ScheduledJobExecution/Update`,
    props
  );

export type scheduledJobExecutionUpdateProps = Omit<
  RestfulShesha.MutateProps<
    ScheduledJobExecutionDtoAjaxResponse,
    AjaxResponseBase,
    void,
    ScheduledJobExecutionDto,
    void
  >,
  'data'
>;
export const scheduledJobExecutionUpdate = (data: ScheduledJobExecutionDto, props: scheduledJobExecutionUpdateProps) =>
  RestfulShesha.mutate<ScheduledJobExecutionDtoAjaxResponse, AjaxResponseBase, void, ScheduledJobExecutionDto, void>(
    'PUT',
    `/api/services/Scheduler/ScheduledJobExecution/Update`,
    data,
    props
  );

export interface ScheduledJobExecutionDeleteQueryParams {
  id?: string;
}

export type ScheduledJobExecutionDeleteProps = Omit<
  MutateProps<void, unknown, ScheduledJobExecutionDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const ScheduledJobExecutionDelete = (props: ScheduledJobExecutionDeleteProps) => (
  <Mutate<void, unknown, ScheduledJobExecutionDeleteQueryParams, void, void>
    verb="DELETE"
    path={`/api/services/Scheduler/ScheduledJobExecution/Delete`}
    {...props}
  />
);

export type UseScheduledJobExecutionDeleteProps = Omit<
  UseMutateProps<void, unknown, ScheduledJobExecutionDeleteQueryParams, void, void>,
  'path' | 'verb'
>;

export const useScheduledJobExecutionDelete = (props: UseScheduledJobExecutionDeleteProps) =>
  useMutate<void, unknown, ScheduledJobExecutionDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/Scheduler/ScheduledJobExecution/Delete`,
    { ...props }
  );

export type scheduledJobExecutionDeleteProps = Omit<
  RestfulShesha.MutateProps<void, unknown, ScheduledJobExecutionDeleteQueryParams, void, void>,
  'data'
>;
export const scheduledJobExecutionDelete = (props: scheduledJobExecutionDeleteProps) =>
  RestfulShesha.mutate<void, unknown, ScheduledJobExecutionDeleteQueryParams, void, void>(
    'DELETE',
    `/api/services/Scheduler/ScheduledJobExecution/Delete`,
    undefined,
    props
  );
