/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export interface AuthenticateModel {
  userNameOrEmailAddress: string;
  password: string;
  /**
   * Optional IMEI number. Is used for mobile applications
   */
  imei?: string | null;
}

export interface AuthenticateResultModel {
  accessToken?: string | null;
  encryptedAccessToken?: string | null;
  expireInSeconds?: number;
  expireOn?: string;
  userId?: number;
  personId?: string | null;
  deviceName?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface AuthenticateResultModelAjaxResponse {
  result?: AuthenticateResultModel;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface BooleanAjaxResponse {
  result?: boolean;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface ExternalLoginProviderInfoModel {
  name?: string | null;
  clientId?: string | null;
}

export interface ExternalLoginProviderInfoModelListAjaxResponse {
  result?: ExternalLoginProviderInfoModel[] | null;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface ExternalAuthenticateModel {
  authProvider: string;
  providerKey: string;
  providerAccessCode: string;
}

export interface ExternalAuthenticateResultModel {
  accessToken?: string | null;
  encryptedAccessToken?: string | null;
  expireInSeconds?: number;
  waitingForActivation?: boolean;
}

export interface ExternalAuthenticateResultModelAjaxResponse {
  result?: ExternalAuthenticateResultModel;
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export type TokenAuthAuthenticateProps = Omit<
  MutateProps<AuthenticateResultModelAjaxResponse, AjaxResponseBase, void, AuthenticateModel>,
  'path' | 'verb'
>;

export const TokenAuthAuthenticate = (props: TokenAuthAuthenticateProps) => (
  <Mutate<AuthenticateResultModelAjaxResponse, AjaxResponseBase, void, AuthenticateModel>
    verb="POST"
    path={`/api/TokenAuth/Authenticate`}
    {...props}
  />
);

export type UseTokenAuthAuthenticateProps = Omit<
  UseMutateProps<AuthenticateResultModelAjaxResponse, void, AuthenticateModel>,
  'path' | 'verb'
>;

export const useTokenAuthAuthenticate = (props: UseTokenAuthAuthenticateProps) =>
  useMutate<AuthenticateResultModelAjaxResponse, AjaxResponseBase, void, AuthenticateModel>(
    'POST',
    `/api/TokenAuth/Authenticate`,
    props
  );

export type TokenAuthSignOffProps = Omit<
  MutateProps<BooleanAjaxResponse, AjaxResponseBase, void, void>,
  'path' | 'verb'
>;

export const TokenAuthSignOff = (props: TokenAuthSignOffProps) => (
  <Mutate<BooleanAjaxResponse, AjaxResponseBase, void, void> verb="POST" path={`/api/TokenAuth/SignOff`} {...props} />
);

export type UseTokenAuthSignOffProps = Omit<UseMutateProps<BooleanAjaxResponse, void, void>, 'path' | 'verb'>;

export const useTokenAuthSignOff = (props: UseTokenAuthSignOffProps) =>
  useMutate<BooleanAjaxResponse, AjaxResponseBase, void, void>('POST', `/api/TokenAuth/SignOff`, props);

export type TokenAuthGetExternalAuthenticationProvidersProps = Omit<
  GetProps<ExternalLoginProviderInfoModelListAjaxResponse, AjaxResponseBase, void>,
  'path'
>;

export const TokenAuthGetExternalAuthenticationProviders = (
  props: TokenAuthGetExternalAuthenticationProvidersProps
) => (
  <Get<ExternalLoginProviderInfoModelListAjaxResponse, AjaxResponseBase, void>
    path={`/api/TokenAuth/GetExternalAuthenticationProviders`}
    {...props}
  />
);

export type UseTokenAuthGetExternalAuthenticationProvidersProps = Omit<
  UseGetProps<ExternalLoginProviderInfoModelListAjaxResponse, void>,
  'path'
>;

export const useTokenAuthGetExternalAuthenticationProviders = (
  props: UseTokenAuthGetExternalAuthenticationProvidersProps
) =>
  useGet<ExternalLoginProviderInfoModelListAjaxResponse, AjaxResponseBase, void>(
    `/api/TokenAuth/GetExternalAuthenticationProviders`,
    props
  );

export type TokenAuthExternalAuthenticateProps = Omit<
  MutateProps<ExternalAuthenticateResultModelAjaxResponse, AjaxResponseBase, void, ExternalAuthenticateModel>,
  'path' | 'verb'
>;

export const TokenAuthExternalAuthenticate = (props: TokenAuthExternalAuthenticateProps) => (
  <Mutate<ExternalAuthenticateResultModelAjaxResponse, AjaxResponseBase, void, ExternalAuthenticateModel>
    verb="POST"
    path={`/api/TokenAuth/ExternalAuthenticate`}
    {...props}
  />
);

export type UseTokenAuthExternalAuthenticateProps = Omit<
  UseMutateProps<ExternalAuthenticateResultModelAjaxResponse, void, ExternalAuthenticateModel>,
  'path' | 'verb'
>;

export const useTokenAuthExternalAuthenticate = (props: UseTokenAuthExternalAuthenticateProps) =>
  useMutate<ExternalAuthenticateResultModelAjaxResponse, AjaxResponseBase, void, ExternalAuthenticateModel>(
    'POST',
    `/api/TokenAuth/ExternalAuthenticate`,
    props
  );
