/* Generated by restful-react */

import React from 'react';
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react';
export const SPEC_VERSION = 'v1';
export interface AuthenticateModel {
  userNameOrEmailAddress: string;
  password: string;
  imei?: string | null;
}

export interface AuthenticateResultModel {
  accessToken?: string | null;
  encryptedAccessToken?: string | null;
  expireInSeconds?: number;
  expireOn?: string;
  userId?: number;
  personId?: string | null;
  deviceName?: string | null;
}

export interface ValidationErrorInfo {
  message?: string | null;
  members?: string[] | null;
}

export interface ErrorInfo {
  code?: number;
  message?: string | null;
  details?: string | null;
  validationErrors?: ValidationErrorInfo[] | null;
}

export interface AuthenticateResultModelAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: AuthenticateResultModel;
}

export interface AjaxResponseBase {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
}

export interface BooleanAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: boolean;
}

export interface ExternalLoginProviderInfoModel {
  name?: string | null;
  clientId?: string | null;
}

export interface ExternalLoginProviderInfoModelListAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ExternalLoginProviderInfoModel[] | null;
}

export interface ExternalAuthenticateModel {
  authProvider: string;
  providerKey: string;
  providerAccessCode: string;
}

export interface ExternalAuthenticateResultModel {
  accessToken?: string | null;
  encryptedAccessToken?: string | null;
  expireInSeconds?: number;
  waitingForActivation?: boolean;
}

export interface ExternalAuthenticateResultModelAjaxResponse {
  targetUrl?: string | null;
  success?: boolean;
  error?: ErrorInfo;
  unAuthorizedRequest?: boolean;
  __abp?: boolean;
  result?: ExternalAuthenticateResultModel;
}

export interface TokenAuthAuthenticateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type TokenAuthAuthenticateProps = Omit<
  MutateProps<
    AuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    TokenAuthAuthenticateQueryParams,
    AuthenticateModel,
    void
  >,
  'path' | 'verb'
>;

export const TokenAuthAuthenticate = (props: TokenAuthAuthenticateProps) => (
  <Mutate<
    AuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    TokenAuthAuthenticateQueryParams,
    AuthenticateModel,
    void
  >
    verb="POST"
    path={`/api/TokenAuth/Authenticate`}
    {...props}
  />
);

export type UseTokenAuthAuthenticateProps = Omit<
  UseMutateProps<
    AuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    TokenAuthAuthenticateQueryParams,
    AuthenticateModel,
    void
  >,
  'path' | 'verb'
>;

export const useTokenAuthAuthenticate = (props: UseTokenAuthAuthenticateProps) =>
  useMutate<
    AuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    TokenAuthAuthenticateQueryParams,
    AuthenticateModel,
    void
  >('POST', `/api/TokenAuth/Authenticate`, props);

export interface TokenAuthSignOffQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type TokenAuthSignOffProps = Omit<
  MutateProps<BooleanAjaxResponse, AjaxResponseBase, TokenAuthSignOffQueryParams, void, void>,
  'path' | 'verb'
>;

export const TokenAuthSignOff = (props: TokenAuthSignOffProps) => (
  <Mutate<BooleanAjaxResponse, AjaxResponseBase, TokenAuthSignOffQueryParams, void, void>
    verb="POST"
    path={`/api/TokenAuth/SignOff`}
    {...props}
  />
);

export type UseTokenAuthSignOffProps = Omit<
  UseMutateProps<BooleanAjaxResponse, AjaxResponseBase, TokenAuthSignOffQueryParams, void, void>,
  'path' | 'verb'
>;

export const useTokenAuthSignOff = (props: UseTokenAuthSignOffProps) =>
  useMutate<BooleanAjaxResponse, AjaxResponseBase, TokenAuthSignOffQueryParams, void, void>(
    'POST',
    `/api/TokenAuth/SignOff`,
    props
  );

export interface TokenAuthGetExternalAuthenticationProvidersQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type TokenAuthGetExternalAuthenticationProvidersProps = Omit<
  GetProps<
    ExternalLoginProviderInfoModelListAjaxResponse,
    AjaxResponseBase,
    TokenAuthGetExternalAuthenticationProvidersQueryParams,
    void
  >,
  'path'
>;

export const TokenAuthGetExternalAuthenticationProviders = (
  props: TokenAuthGetExternalAuthenticationProvidersProps
) => (
  <Get<
    ExternalLoginProviderInfoModelListAjaxResponse,
    AjaxResponseBase,
    TokenAuthGetExternalAuthenticationProvidersQueryParams,
    void
  >
    path={`/api/TokenAuth/GetExternalAuthenticationProviders`}
    {...props}
  />
);

export type UseTokenAuthGetExternalAuthenticationProvidersProps = Omit<
  UseGetProps<
    ExternalLoginProviderInfoModelListAjaxResponse,
    AjaxResponseBase,
    TokenAuthGetExternalAuthenticationProvidersQueryParams,
    void
  >,
  'path'
>;

export const useTokenAuthGetExternalAuthenticationProviders = (
  props: UseTokenAuthGetExternalAuthenticationProvidersProps
) =>
  useGet<
    ExternalLoginProviderInfoModelListAjaxResponse,
    AjaxResponseBase,
    TokenAuthGetExternalAuthenticationProvidersQueryParams,
    void
  >(`/api/TokenAuth/GetExternalAuthenticationProviders`, props);

export interface TokenAuthExternalAuthenticateQueryParams {
  /**
   * The requested API version
   */
  'api-version'?: string;
}

export type TokenAuthExternalAuthenticateProps = Omit<
  MutateProps<
    ExternalAuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    TokenAuthExternalAuthenticateQueryParams,
    ExternalAuthenticateModel,
    void
  >,
  'path' | 'verb'
>;

export const TokenAuthExternalAuthenticate = (props: TokenAuthExternalAuthenticateProps) => (
  <Mutate<
    ExternalAuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    TokenAuthExternalAuthenticateQueryParams,
    ExternalAuthenticateModel,
    void
  >
    verb="POST"
    path={`/api/TokenAuth/ExternalAuthenticate`}
    {...props}
  />
);

export type UseTokenAuthExternalAuthenticateProps = Omit<
  UseMutateProps<
    ExternalAuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    TokenAuthExternalAuthenticateQueryParams,
    ExternalAuthenticateModel,
    void
  >,
  'path' | 'verb'
>;

export const useTokenAuthExternalAuthenticate = (props: UseTokenAuthExternalAuthenticateProps) =>
  useMutate<
    ExternalAuthenticateResultModelAjaxResponse,
    AjaxResponseBase,
    TokenAuthExternalAuthenticateQueryParams,
    ExternalAuthenticateModel,
    void
  >('POST', `/api/TokenAuth/ExternalAuthenticate`, props);
